import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#414750',
        'inverse-surface': '#2f3033',
        'on-surface': '#1a1c1e',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#0061a4',
        'surface-container': '#eeedf0',
        'surface-bright': '#faf9fc',
        'on-primary': '#ffffff',
        'surface-container-low': '#f4f3f6',
        'inverse-primary': '#9fcaff',
        'on-secondary': '#ffffff',
        'secondary-container': '#d7e3f8',
        'secondary': '#535f70',
        'outline-variant': '#c1c7d2',
        'on-tertiary-container': '#e9d0f7',
        'tertiary-container': '#6b5778',
        'on-tertiary': '#ffffff',
        'outline': '#717782',
        'surface-container-high': '#e8e8eb',
        'on-primary-container': '#c0dbff',
        'background': '#faf9fc',
        'on-secondary-container': '#596576',
        'surface-variant': '#e3e2e5',
        'surface': '#faf9fc',
        'inverse-on-surface': '#f1f0f3',
        'surface-dim': '#dadadc',
        'on-error': '#ffffff',
        'surface-container-highest': '#e3e2e5',
        'on-background': '#1a1c1e',
        'primary': '#00497d',
        'error-container': '#ffdad6',
      },
      fontFamily: {
        sans: ['Noto Sans JP', 'sans-serif'],
      },
      fontSize: {
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0.15px', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
} satisfies Config
